### ISSUE TITLE
Song playback?

### ISSUE THREAD

**Issue by Wrathrowe** [GodTamIt/.NET-Google-Music-API#2]
Hey,

I just came across your API, it looks and works great! Would you be able to point me in the right direction to get the songs to play?

Thanks!

**Comment by GodTamIt** [comment]
Hey, currently the API does not support streaming, but that is definitely a planned feature for the future. Google supports streaming via the Google Play Music web and mobile apps, but in future releases, the API will support the chunked streaming that Google provides.

Let me know if you have any other questions!
